export interface ILodge{
    lodgeId?                    : number;
    lodgeName?                  : string;
    description?                : string;
    checkIn?                    : Date;
    checkOut?                   : Date;
    nightPrice?                 : number;
    latitude?                   : number;
    longitude?                  : number;
    totalRate?                  : number;
    images?                     : string;
    type?                       : string;
    amenities?                  : string;
    operational?                : boolean;
    creationDatetime?           : Date;
    creationResponsible?        : number;
    lastUpdateDatetime?         : Date;
    updateResponsible?          : number;
}